# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0017_auto_20160308_1251'),
    ]

    operations = [
        # migrations.RenameModel('PlantBarrierByRegion', 'PlantBarrier'),
    ]
