# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0003_auto_20160707_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeedsType',
            new_name='Human_Needs_Library',
        ),
    ]
