# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.AuthUser'),
        ),
    ]
