# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantnutrientrquirementsbyregion',
            options={'managed': True},
        ),
    ]
