# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0002_id_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='spc_project',
            name='polyculture_coordinates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='human_needs_library',
            name='need',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spc_project',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
