# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'barrier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantBarrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Barrier')),
                ('plants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant')),
                ('regions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region')),
            ],
            options={
                'db_table': 'plants_barrier',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='barrier',
            field=models.ManyToManyField(through='plants.PlantBarrier', to='plants.Barrier'),
        ),
        migrations.AlterUniqueTogether(
            name='plantbarrier',
            unique_together=set([('plants', 'regions')]),
        ),
    ]
