# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_auto_20160307_1701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantbarrier',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='plantbarrier',
            name='barrier',
        ),
        migrations.RemoveField(
            model_name='plantbarrier',
            name='plants',
        ),
        migrations.RemoveField(
            model_name='plantbarrier',
            name='regions',
        ),
        migrations.AlterUniqueTogether(
            name='plantregion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='plantregion',
            name='plants',
        ),
        migrations.RemoveField(
            model_name='plantregion',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='barrier',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='region',
        ),
        migrations.DeleteModel(
            name='PlantBarrier',
        ),
        migrations.DeleteModel(
            name='PlantRegion',
        ),
    ]
