# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_auto_20160307_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'image_urls',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='urltags',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='plant',
            name='tags',
            field=models.URLField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='imageurl',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='imageurl',
            name='value',
            field=models.URLField(blank=True, null=True),
        ),
    ]
