# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0015_auto_20160308_1152'),
    ]

    operations = [
    ]
