# Generated by Django 2.0.4 on 2018-06-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20160731_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': True},
        ),
    ]
