# Generated by Django 2.0.4 on 2018-06-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20180626_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='affiliation',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='experience',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='interestes',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
