# Generated by Django 2.0.4 on 2018-06-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20180626_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='interestes',
            new_name='interests',
        ),
    ]
