# Generated by Django 2.0.6 on 2018-07-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20180626_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_data_import',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
