# Generated by Django 2.0.7 on 2018-10-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20181022_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='is_data_import',
            field=models.NullBooleanField(),
        ),
    ]
