# Generated by Django 4.0.4 on 2022-05-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20190923_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='is_data_import',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
