# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20160303_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDimensionsByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant')),
                ('regions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('root_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'plants_dimensions_by_region',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='dimensions',
            field=models.ManyToManyField(to='plants.PlantDimensionsByRegion'),
        ),
    ]
