# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_auto_20160307_1646'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantbarrier',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='plantbarrier',
            name='barrier',
        ),
        migrations.RemoveField(
            model_name='plantbarrier',
            name='plants',
        ),
        migrations.RemoveField(
            model_name='plantbarrier',
            name='regions',
        ),
        migrations.AlterUniqueTogether(
            name='plantregion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='plantregion',
            name='plants',
        ),
        migrations.RemoveField(
            model_name='plantregion',
            name='regions',
        ),
        migrations.AlterUniqueTogether(
            name='plantrootdepthatmaturitybyregion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='plantrootdepthatmaturitybyregion',
            name='plants',
        ),
        migrations.RemoveField(
            model_name='plantrootdepthatmaturitybyregion',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='barrier',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='height',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='region',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='root_depth',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='spread',
        ),
        migrations.DeleteModel(
            name='PlantBarrier',
        ),
        migrations.DeleteModel(
            name='PlantRegion',
        ),
        migrations.DeleteModel(
            name='PlantRootDepthAtMaturityByRegion',
        ),
    ]
