# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0016_auto_20160308_1248'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plantbarrier',
            table='plants_barrier_by_region',
        ),
    ]
