# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0018_auto_20160308_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urltags',
            options={'managed': False},
        ),
    ]
