# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0019_auto_20160308_1310'),
    ]

    operations = [
    	migrations.RenameModel("PlantBarrier", "PlantBarrierByRegion"),
    ]
