# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.CharField(max_length=500)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'Human_Needs_Library',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Needs',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
