# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0002_auto_20160707_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needstype',
            name='need',
            field=models.TextField(),
        ),
    ]
