# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0005_chosen_human_needs_chosen_plants_spc_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
            ],
            options={
                'db_table': 'SPC_Project',
                'managed': True,
            },
        ),
    ]
