# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0006_id_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='id_table',
            table='ID_Table',
        ),
    ]
