# Generated by Django 2.0.6 on 2018-07-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_transactions_parent_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='citation',
            new_name='reference',
        ),
    ]
