# Generated by Django 2.0.7 on 2018-10-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20180711_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='scientific_names',
        ),
        migrations.AddField(
            model_name='actions',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
