# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 00:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGrowthPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'active_growth_period',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Allelopathic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'allelopathic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'animals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BiochemicalMaterialProd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'biochemical_material_prod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CanopyDensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'canopy_density',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CulturalAndAmenityProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cultural_and_amenity_prod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DroughtTol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drought_tol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'duration',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EndemicStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'endemic_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ErosionControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'erosion_control',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FireTol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fire_tol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FloodTol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flood_tol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FlowerColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flower_color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FoliageColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'foliage_color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FoodProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'food_prod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FruitColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fruit_color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HarvestPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'harvest_period',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HumidityTol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'humidity_tol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Insects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'layer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeafRetention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leaf_retention',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lifespan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lifespan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LivestockBloat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'livestock_bloat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicinalsProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medicinals_prod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MineralNutrientsProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mineral_nutrients_prod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NutrientRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nutrient_requirements',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantActiveGrowthPeriodByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_active_growth_period_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantAnimalAttractorByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_animal_attractor_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantAnimalRegulatorByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_animal_regulator_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantBiochemicalMaterialProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_biochemical_material_prod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantCanopyDensityByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_canopy_density_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantCulturalAndAmenityProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_cultural_and_amenity_prod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantDurationByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_duration_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantEndemicStatusByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_endemic_status_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantErosionControlByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_erosion_control_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantFlowerColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_flower_color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantFoliageColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_foliage_color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantFoodProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_food_prod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantFruitColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_fruit_color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantHarvestPeriodByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_harvest_period_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantInsectAttractorByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_insect_attractor_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantInsectRegulatorByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_insect_regulator_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_layer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantLeafRetentionByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_leaf_retention_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantMedicinalsProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_medicinals_prod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantMineralNutrientsProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_mineral_nutrients_prod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantNutrientRequirementsByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_nutrient_requirements_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantRawMaterialsProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_raw_materials_prod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantShadeTolByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_shade_tol_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantSoilDrainageTolByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_soil_drainage_tol_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantSpreadAtMaturityByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'plants_spread_at_maturity_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantSunNeedsByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_sun_needs_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantWaterNeedsByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'plants_water_needs_by_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RawMaterialsProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_materials_prod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'regions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SaltTol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salt_tol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShadeTol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shade_tol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SoilDrainageTol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'soil_drainage_tol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SunNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sun_needs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Toxicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toxicity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ToxinRemoval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toxin_removal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UrlTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'url_tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WaterNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'water_needs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WindTol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wind_tol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnimalFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animal_food',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DegreeOfSerotiny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'degree_of_serotiny',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(blank=True, max_length=160, null=True)),
                ('species', models.CharField(blank=True, max_length=160, null=True)),
                ('variety', models.CharField(blank=True, max_length=160, null=True)),
                ('common_name', models.CharField(blank=True, max_length=160, null=True)),
                ('tags', models.CharField(blank=True, max_length=160, null=True)),
                ('ph_min', models.DecimalField(blank=True, db_column='ph_min', decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(14, message='ph should be in range 0-14')])),
                ('ph_max', models.DecimalField(blank=True, db_column='ph_max', decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(14, message='ph should be in range 0-14')])),
                ('minimum_temperature_tol', models.IntegerField(blank=True, null=True)),
                ('innoculant', models.CharField(blank=True, max_length=160, null=True)),
                ('allelochemicals', models.CharField(blank=True, max_length=160, null=True)),
                ('active_growth_period', models.ManyToManyField(through='plants.PlantActiveGrowthPeriodByRegion', to=b'plants.ActiveGrowthPeriod')),
                ('allelopathic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Allelopathic')),
            ],
            options={
                'db_table': 'plants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantAnimalFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.AnimalFood')),
                ('plants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant')),
            ],
            options={
                'db_table': 'plants_animal_food',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Serotiny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'serotiny',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TheFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'the_family',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TheFamilyCommonName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'the_family_common_name',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='animal_food',
            field=models.ManyToManyField(through='plants.PlantAnimalFood', to=b'plants.AnimalFood'),
        ),
        migrations.AddField(
            model_name='plant',
            name='biochemical_material_prod',
            field=models.ManyToManyField(through='plants.PlantBiochemicalMaterialProd', to=b'plants.BiochemicalMaterialProd'),
        ),
        migrations.AddField(
            model_name='plant',
            name='canopy_density',
            field=models.ManyToManyField(through='plants.PlantCanopyDensityByRegion', to=b'plants.CanopyDensity'),
        ),
        migrations.AddField(
            model_name='plant',
            name='cultural_and_amenity_prod',
            field=models.ManyToManyField(through='plants.PlantCulturalAndAmenityProd', to=b'plants.CulturalAndAmenityProd'),
        ),
        migrations.AddField(
            model_name='plant',
            name='degree_of_serotiny',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.DegreeOfSerotiny'),
        ),
        migrations.AddField(
            model_name='plant',
            name='drought_tol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.DroughtTol'),
        ),
        migrations.AddField(
            model_name='plant',
            name='duration',
            field=models.ManyToManyField(through='plants.PlantDurationByRegion', to=b'plants.Duration'),
        ),
        migrations.AddField(
            model_name='plant',
            name='endemic_status',
            field=models.ManyToManyField(through='plants.PlantEndemicStatusByRegion', to=b'plants.EndemicStatus'),
        ),
        migrations.AddField(
            model_name='plant',
            name='erosion_control',
            field=models.ManyToManyField(through='plants.PlantErosionControlByRegion', to=b'plants.ErosionControl'),
        ),
        migrations.AddField(
            model_name='plant',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.TheFamily'),
        ),
        migrations.AddField(
            model_name='plant',
            name='family_common_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.TheFamilyCommonName'),
        ),
        migrations.AddField(
            model_name='plant',
            name='fire_tol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.FireTol'),
        ),
        migrations.AddField(
            model_name='plant',
            name='flood_tol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.FloodTol'),
        ),
        migrations.AddField(
            model_name='plant',
            name='flower_color',
            field=models.ManyToManyField(through='plants.PlantFlowerColor', to=b'plants.FlowerColor'),
        ),
        migrations.AddField(
            model_name='plant',
            name='foliage_color',
            field=models.ManyToManyField(through='plants.PlantFoliageColor', to=b'plants.FoliageColor'),
        ),
        migrations.AddField(
            model_name='plant',
            name='food_prod',
            field=models.ManyToManyField(through='plants.PlantFoodProd', to=b'plants.FoodProd'),
        ),
        migrations.AddField(
            model_name='plant',
            name='fruit_color',
            field=models.ManyToManyField(through='plants.PlantFruitColor', to=b'plants.FruitColor'),
        ),
        migrations.AddField(
            model_name='plant',
            name='harvest_period',
            field=models.ManyToManyField(through='plants.PlantHarvestPeriodByRegion', to=b'plants.HarvestPeriod'),
        ),
        migrations.AddField(
            model_name='plant',
            name='humidity_tol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.HumidityTol'),
        ),
        migrations.AddField(
            model_name='plant',
            name='layer',
            field=models.ManyToManyField(through='plants.PlantLayer', to=b'plants.Layer'),
        ),
        migrations.AddField(
            model_name='plant',
            name='leaf_retention',
            field=models.ManyToManyField(through='plants.PlantLeafRetentionByRegion', to=b'plants.LeafRetention'),
        ),
        migrations.AddField(
            model_name='plant',
            name='lifespan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Lifespan'),
        ),
        migrations.AddField(
            model_name='plant',
            name='livestock_bloat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.LivestockBloat'),
        ),
        migrations.AddField(
            model_name='plant',
            name='medicinals_prod',
            field=models.ManyToManyField(through='plants.PlantMedicinalsProd', to=b'plants.MedicinalsProd'),
        ),
        migrations.AddField(
            model_name='plant',
            name='mineral_nutrients_prod',
            field=models.ManyToManyField(through='plants.PlantMineralNutrientsProd', to=b'plants.MineralNutrientsProd'),
        ),
        migrations.AddField(
            model_name='plant',
            name='plants_animal_attractor',
            field=models.ManyToManyField(related_name='a_plants_animal_attractor_related', through='plants.PlantAnimalAttractorByRegion', to=b'plants.Animals'),
        ),
        migrations.AddField(
            model_name='plant',
            name='plants_animal_regulator',
            field=models.ManyToManyField(through='plants.PlantAnimalRegulatorByRegion', to=b'plants.Animals'),
        ),
        migrations.AddField(
            model_name='plant',
            name='plants_insect_attractor',
            field=models.ManyToManyField(related_name='a_plants_insect_attractor_related', through='plants.PlantInsectAttractorByRegion', to=b'plants.Insects'),
        ),
        migrations.AddField(
            model_name='plant',
            name='plants_insect_regulator',
            field=models.ManyToManyField(through='plants.PlantInsectRegulatorByRegion', to=b'plants.Insects'),
        ),
        migrations.AddField(
            model_name='plant',
            name='salt_tol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.SaltTol'),
        ),
        migrations.AddField(
            model_name='plant',
            name='serotiny',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Serotiny'),
        ),
        migrations.AddField(
            model_name='plant',
            name='shade_tol',
            field=models.ManyToManyField(through='plants.PlantShadeTolByRegion', to=b'plants.ShadeTol'),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil_drainage_tol',
            field=models.ManyToManyField(through='plants.PlantSoilDrainageTolByRegion', to=b'plants.SoilDrainageTol'),
        ),
        migrations.AddField(
            model_name='plant',
            name='spread',
            field=models.ManyToManyField(to=b'plants.PlantSpreadAtMaturityByRegion'),
        ),
        migrations.AddField(
            model_name='plant',
            name='sun_needs',
            field=models.ManyToManyField(through='plants.PlantSunNeedsByRegion', to=b'plants.SunNeeds'),
        ),
        migrations.AddField(
            model_name='plant',
            name='toxicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Toxicity'),
        ),
        migrations.AddField(
            model_name='plant',
            name='toxin_removal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.ToxinRemoval'),
        ),
        migrations.AddField(
            model_name='plant',
            name='water_needs',
            field=models.ManyToManyField(through='plants.PlantWaterNeedsByRegion', to=b'plants.WaterNeeds'),
        ),
        migrations.AddField(
            model_name='plant',
            name='wind_tol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.WindTol'),
        ),
        migrations.CreateModel(
            name='PlantBehavior',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('plants.plant',),
        ),
        migrations.CreateModel(
            name='PlantCharacteristic',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('plants.plant',),
        ),
        migrations.CreateModel(
            name='PlantID',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('plants.plant',),
        ),
        migrations.CreateModel(
            name='PlantNeed',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('plants.plant',),
        ),
        migrations.CreateModel(
            name='PlantProduct',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('plants.plant',),
        ),
        migrations.CreateModel(
            name='PlantTolerance',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('plants.plant',),
        ),
        migrations.CreateModel(
            name='Barrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'barrier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantBarrierByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Barrier')),
                ('plants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant')),
                ('regions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region')),
            ],
            options={
                'db_table': 'plants_barrier_by_region',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='barrier',
            field=models.ManyToManyField(through='plants.PlantBarrierByRegion', to=b'plants.Barrier'),
        ),
        migrations.CreateModel(
            name='PlantRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('root_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('plants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant')),
                ('regions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region')),
            ],
            options={
                'db_table': 'plants_region',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='plant',
            name='barrier',
        ),
        migrations.AddField(
            model_name='plant',
            name='region',
            field=models.ManyToManyField(through='plants.PlantRegion', to=b'plants.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='plantregion',
            unique_together=set([('plants', 'regions')]),
        ),
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'image_urls',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='urltags',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='plant',
            name='tags',
            field=models.URLField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='imageurl',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='imageurl',
            name='value',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='urltags',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='PlantScientificName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plants_scientific_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScientificName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scientific_name',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='ph_max',
            new_name='pH_max',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='ph_min',
            new_name='pH_min',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='species',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='variety',
        ),
        migrations.AlterField(
            model_name='plant',
            name='animal_food',
            field=models.ManyToManyField(through='plants.PlantAnimalFood', to=b'plants.AnimalFood', verbose_name='animal food'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='biochemical_material_prod',
            field=models.ManyToManyField(through='plants.PlantBiochemicalMaterialProd', to=b'plants.BiochemicalMaterialProd', verbose_name='biochemical materials'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='cultural_and_amenity_prod',
            field=models.ManyToManyField(through='plants.PlantCulturalAndAmenityProd', to=b'plants.CulturalAndAmenityProd', verbose_name='cultrual and amenity'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='medicinals_prod',
            field=models.ManyToManyField(through='plants.PlantMedicinalsProd', to=b'plants.MedicinalsProd', verbose_name='medicinals'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='mineral_nutrients_prod',
            field=models.ManyToManyField(through='plants.PlantMineralNutrientsProd', to=b'plants.MineralNutrientsProd', verbose_name='mineral nutrients'),
        ),
        migrations.AddField(
            model_name='plant',
            name='raw_materials_prod',
            field=models.ManyToManyField(through='plants.PlantRawMaterialsProd', to=b'plants.RawMaterialsProd', verbose_name='raw materials'),
        ),
        migrations.AddField(
            model_name='plantscientificname',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantscientificname',
            name='scientific_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.ScientificName'),
        ),
        migrations.AddField(
            model_name='plantnutrientrequirementsbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantnutrientrequirementsbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plant',
            name='scientific_name',
            field=models.ManyToManyField(through='plants.PlantScientificName', to=b'plants.ScientificName'),
        ),
        migrations.AlterUniqueTogether(
            name='plantnutrientrequirementsbyregion',
            unique_together=set([('plants', 'regions')]),
        ),
        migrations.AddField(
            model_name='plantactivegrowthperiodbyregion',
            name='active_growth_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.ActiveGrowthPeriod'),
        ),
        migrations.AddField(
            model_name='plantactivegrowthperiodbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantactivegrowthperiodbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantanimalattractorbyregion',
            name='animals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Animals'),
        ),
        migrations.AddField(
            model_name='plantanimalattractorbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantanimalattractorbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantanimalregulatorbyregion',
            name='animals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Animals'),
        ),
        migrations.AddField(
            model_name='plantanimalregulatorbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantanimalregulatorbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantbiochemicalmaterialprod',
            name='biochemical_material_prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.BiochemicalMaterialProd'),
        ),
        migrations.AddField(
            model_name='plantbiochemicalmaterialprod',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantcanopydensitybyregion',
            name='canopy_density',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.CanopyDensity'),
        ),
        migrations.AddField(
            model_name='plantcanopydensitybyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantcanopydensitybyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantculturalandamenityprod',
            name='cultural_and_amenity_prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.CulturalAndAmenityProd'),
        ),
        migrations.AddField(
            model_name='plantculturalandamenityprod',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantdurationbyregion',
            name='duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Duration'),
        ),
        migrations.AddField(
            model_name='plantdurationbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantdurationbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantendemicstatusbyregion',
            name='endemic_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.EndemicStatus'),
        ),
        migrations.AddField(
            model_name='plantendemicstatusbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantendemicstatusbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='planterosioncontrolbyregion',
            name='erosion_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.ErosionControl'),
        ),
        migrations.AddField(
            model_name='planterosioncontrolbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='planterosioncontrolbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantflowercolor',
            name='flower_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.FlowerColor'),
        ),
        migrations.AddField(
            model_name='plantflowercolor',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantfoliagecolor',
            name='foliage_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.FoliageColor'),
        ),
        migrations.AddField(
            model_name='plantfoliagecolor',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantfoodprod',
            name='food_prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.FoodProd'),
        ),
        migrations.AddField(
            model_name='plantfoodprod',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantfruitcolor',
            name='fruit_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.FruitColor'),
        ),
        migrations.AddField(
            model_name='plantfruitcolor',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantharvestperiodbyregion',
            name='harvest_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.HarvestPeriod'),
        ),
        migrations.AddField(
            model_name='plantharvestperiodbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantharvestperiodbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantinsectattractorbyregion',
            name='insects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Insects'),
        ),
        migrations.AddField(
            model_name='plantinsectattractorbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantinsectattractorbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantinsectregulatorbyregion',
            name='insects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Insects'),
        ),
        migrations.AddField(
            model_name='plantinsectregulatorbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantinsectregulatorbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantlayer',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Layer'),
        ),
        migrations.AddField(
            model_name='plantlayer',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantleafretentionbyregion',
            name='leaf_retention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.LeafRetention'),
        ),
        migrations.AddField(
            model_name='plantleafretentionbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantleafretentionbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantmedicinalsprod',
            name='medicinals_prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.MedicinalsProd'),
        ),
        migrations.AddField(
            model_name='plantmedicinalsprod',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantmineralnutrientsprod',
            name='mineral_nutrients_prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.MineralNutrientsProd'),
        ),
        migrations.AddField(
            model_name='plantmineralnutrientsprod',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantrawmaterialsprod',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantrawmaterialsprod',
            name='raw_materials_prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.RawMaterialsProd'),
        ),
        migrations.AddField(
            model_name='plantshadetolbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantshadetolbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantshadetolbyregion',
            name='shade_tol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.ShadeTol'),
        ),
        migrations.AddField(
            model_name='plantsoildrainagetolbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantsoildrainagetolbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantsoildrainagetolbyregion',
            name='soil_drainage_tol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.SoilDrainageTol'),
        ),
        migrations.AddField(
            model_name='plantsunneedsbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantsunneedsbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantsunneedsbyregion',
            name='sun_needs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.SunNeeds'),
        ),
        migrations.AddField(
            model_name='plantwaterneedsbyregion',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='plantwaterneedsbyregion',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='plantwaterneedsbyregion',
            name='water_needs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.WaterNeeds'),
        ),
        migrations.AddField(
            model_name='urltags',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
        migrations.AlterUniqueTogether(
            name='plantcanopydensitybyregion',
            unique_together=set([('plants', 'regions')]),
        ),
        migrations.AlterUniqueTogether(
            name='plantdurationbyregion',
            unique_together=set([('plants', 'regions')]),
        ),
        migrations.AlterUniqueTogether(
            name='planterosioncontrolbyregion',
            unique_together=set([('plants', 'regions')]),
        ),
        migrations.AlterUniqueTogether(
            name='plantleafretentionbyregion',
            unique_together=set([('plants', 'regions')]),
        ),
        migrations.AlterUniqueTogether(
            name='plantsunneedsbyregion',
            unique_together=set([('plants', 'regions')]),
        ),
        migrations.AlterUniqueTogether(
            name='plantwaterneedsbyregion',
            unique_together=set([('plants', 'regions')]),
        ),
        migrations.AlterUniqueTogether(
            name='urltags',
            unique_together=set([('value', 'plants')]),
        ),
    ]
