# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantnutrientrequirementsbyregion',
            name='fertility_needs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.NutrientRequirements'),
        ),
    ]
