# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_auto_20170605_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterneeds',
            name='value',
        ),
        migrations.AddField(
            model_name='waterneeds',
            name='amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterneeds',
            name='frequency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterneeds',
            name='season',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterneeds',
            name='units',
            field=models.TextField(blank=True, null=True),
        ),
    ]
