# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-05 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20170605_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterneeds',
            old_name='water_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='waterneeds',
            old_name='water_frequency',
            new_name='frequency',
        ),
        migrations.RenameField(
            model_name='waterneeds',
            old_name='water_season',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='waterneeds',
            old_name='water_units',
            new_name='units',
        ),
    ]
