# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-06 20:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_auto_20170605_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterneeds',
            name='amount',
        ),
        migrations.AddField(
            model_name='waterneeds',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, message='amount of water should be more than 0')]),
        ),
    ]
