# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'managed': False},
        ),
    ]
