# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_squashed_0004_auto_20160731_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='spread',
        ),
        migrations.AddField(
            model_name='plant',
            name='barrier',
            field=models.ManyToManyField(through='plants.PlantBarrierByRegion', to='plants.Barrier'),
        ),
        migrations.AddField(
            model_name='plant',
            name='nutrient_requirements',
            field=models.ManyToManyField(through='plants.PlantNutrientRequirementsByRegion', to='plants.NutrientRequirements', verbose_name='nutrient requirements'),
        ),
        migrations.AddField(
            model_name='plantnutrientrequirementsbyregion',
            name='nutrient_requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.NutrientRequirements'),
        ),
        migrations.AlterUniqueTogether(
            name='plantbarrierbyregion',
            unique_together=set([('plants', 'regions')]),
        ),
        migrations.DeleteModel(
            name='PlantSpreadAtMaturityByRegion',
        ),
    ]
