# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-03 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20160801_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='innoculant',
            new_name='inoculant',
        ),
        migrations.AddField(
            model_name='plant',
            name='heat_tol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='timetofirstharvest',
            field=models.DecimalField(blank=True, db_column='timetofirstharvest', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='lifespan',
            field=models.DecimalField(blank=True, db_column='lifespan', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='Lifespan',
        ),
    ]
