# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-05 21:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20170605_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'water_frequency',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WaterSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'water_season',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WaterUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'water_units',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='waterneeds',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='waterneeds',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='waterneeds',
            name='season',
        ),
        migrations.RemoveField(
            model_name='waterneeds',
            name='units',
        ),
        migrations.AddField(
            model_name='waterneeds',
            name='water_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, message='should be more than 0')]),
        ),
        migrations.AddField(
            model_name='waterneeds',
            name='water_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.WaterFrequency'),
        ),
        migrations.AddField(
            model_name='waterneeds',
            name='water_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.WaterSeason'),
        ),
        migrations.AddField(
            model_name='waterneeds',
            name='water_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.WaterUnits'),
        ),
    ]
