# Generated by Django 2.0.6 on 2018-07-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_auto_20170606_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantactivegrowthperiodbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
