# Generated by Django 2.0.6 on 2018-07-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_plantactivegrowthperiodbyregion_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantanimalattractorbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantanimalfood',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantanimalregulatorbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantbarrierbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantbiochemicalmaterialprod',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantcanopydensitybyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantculturalandamenityprod',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdurationbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantendemicstatusbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planterosioncontrolbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantflowercolor',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantfoliagecolor',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantfoodprod',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantfruitcolor',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantharvestperiodbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantinsectattractorbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantinsectregulatorbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantlayer',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantleafretentionbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantmedicinalsprod',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantmineralnutrientsprod',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantnutrientrequirementsbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantrawmaterialsprod',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantscientificname',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantshadetolbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantsoildrainagetolbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantsunneedsbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantwaterneedsbyregion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
