# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.TextField()),
                ('property', models.TextField()),
                ('value', models.TextField(blank=True, null=True)),
                ('citation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.TextField(blank=True, null=True)),
                ('plants_id', models.IntegerField(blank=True, null=True)),
                ('ignore', models.BooleanField()),
            ],
            options={
                'db_table': 'transactions',
                'managed': True,
            },
        ),
    ]
