# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20160801_0100'),
        ('login', '0005_auto_20160731_0131'),
        ('frontend', '0001_squashed_0002_auto_20160801_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Region'),
        ),
        migrations.AddField(
            model_name='actions',
            name='scientific_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.ScientificName'),
        ),
        migrations.AddField(
            model_name='actions',
            name='transactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Transactions'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.AuthUser'),
        ),
    ]
