# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0001_squashed_0005_chosen_human_needs_chosen_plants_spc_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID_Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_Value', models.IntegerField()),
            ],
            options={
                'db_table': 'ID_Table',
                'managed': True,
            },
        ),
    ]
