# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20160731_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authgroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={'managed': True},
        ),
    ]
